<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
    xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
    exclude-result-prefixes="sitemap image news">

<xsl:output method="html" encoding="UTF-8" indent="yes"/>

<xsl:template match="/">
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>XML Sitemap — DadsFam SEO</title>
    <style>
        *,*::before,*::after{box-sizing:border-box}
        body{margin:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f0f4f8;color:#1a2332}
        .header{background:linear-gradient(135deg,#1a4fa0,#123a78);padding:28px 40px;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:16px}
        .header-left{display:flex;align-items:center;gap:14px}
        .header-icon{font-size:32px}
        .header-title{color:#fff;font-size:22px;font-weight:800;margin:0}
        .header-sub{color:rgba(255,255,255,.65);font-size:13px;margin:2px 0 0}
        .header-badge{background:rgba(255,255,255,.12);color:rgba(255,255,255,.8);border:1px solid rgba(255,255,255,.2);border-radius:99px;padding:4px 14px;font-size:12px;font-weight:600;font-family:monospace}
        .container{max-width:1100px;margin:32px auto;padding:0 24px}
        .info-bar{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:16px 22px;display:flex;align-items:center;gap:12px;margin-bottom:24px;font-size:13px;color:#475569}
        .info-bar svg{flex-shrink:0;color:#1a4fa0}
        .info-bar strong{color:#1a2332}
        .card{background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;margin-bottom:24px}
        .card-header{background:#f8fafc;border-bottom:1px solid #e2e8f0;padding:14px 22px;display:flex;align-items:center;gap:10px}
        .card-title{font-size:15px;font-weight:700;color:#1a2332;margin:0}
        .card-count{margin-left:auto;background:#e0f2fe;color:#0369a1;border-radius:99px;padding:2px 12px;font-size:12px;font-weight:700}
        table{width:100%;border-collapse:collapse}
        th{text-align:left;padding:10px 22px;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.06em;color:#64748b;background:#f8fafc;border-bottom:1px solid #e2e8f0}
        td{padding:12px 22px;font-size:13px;border-bottom:1px solid #f1f5f9;vertical-align:middle}
        tr:last-child td{border-bottom:none}
        tr:hover td{background:#fafbfc}
        a{color:#1a4fa0;text-decoration:none;font-weight:500;word-break:break-all}
        a:hover{text-decoration:underline;color:#123a78}
        .lastmod{color:#94a3b8;font-size:12px;white-space:nowrap}
        .priority{background:#f0fdf4;color:#166534;border-radius:4px;padding:2px 8px;font-size:11px;font-weight:700}
        .changefreq{color:#64748b;font-size:12px}
        .sitemap-link{display:flex;align-items:center;gap:8px}
        .sitemap-icon{font-size:16px}
        @media(max-width:600px){.header{padding:20px}.container{padding:0 12px}td,th{padding:10px 14px}}
    </style>
</head>
<body>

<div class="header">
    <div class="header-left">
        <span class="header-icon">🏆</span>
        <div>
            <h1 class="header-title">XML Sitemap</h1>
            <p class="header-sub">Generated by DadsFam SEO · Submitted to Google &amp; Bing automatically</p>
        </div>
    </div>
    <span class="header-badge">sitemap.xml</span>
</div>

<div class="container">

    <div class="info-bar">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M12 16v-4M12 8h.01"/></svg>
        <span><strong>This sitemap is for search engines, not humans</strong> — but we made it look nice anyway. Google and Bing use this to discover and index your content. <a href="https://search.google.com/search-console" target="_blank" rel="noopener noreferrer">Submit it in Google Search Console →</a></span>
    </div>

    <!-- Sitemap Index -->
    <xsl:if test="sitemap:sitemapindex">
        <div class="card">
            <div class="card-header">
                <span style="font-size:18px">🗺️</span>
                <span class="card-title">Sitemap Index</span>
                <span class="card-count"><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> sitemaps</span>
            </div>
            <table>
                <tr>
                    <th>Sitemap File</th>
                    <th>Last Updated</th>
                </tr>
                <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                    <xsl:sort select="sitemap:loc"/>
                    <tr>
                        <td>
                            <div class="sitemap-link">
                                <span class="sitemap-icon">📄</span>
                                <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                            </div>
                        </td>
                        <td class="lastmod"><xsl:value-of select="sitemap:lastmod"/></td>
                    </tr>
                </xsl:for-each>
            </table>
        </div>
    </xsl:if>

    <!-- URL Set (individual sitemaps) -->
    <xsl:if test="sitemap:urlset">
        <div class="card">
            <div class="card-header">
                <span style="font-size:18px">🔗</span>
                <span class="card-title">URLs</span>
                <span class="card-count"><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs</span>
            </div>
            <table>
                <tr>
                    <th>URL</th>
                    <th>Last Modified</th>
                    <th>Priority</th>
                    <th>Change Freq</th>
                </tr>
                <xsl:for-each select="sitemap:urlset/sitemap:url">
                    <tr>
                        <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
                        <td class="lastmod"><xsl:value-of select="sitemap:lastmod"/></td>
                        <td>
                            <xsl:if test="sitemap:priority">
                                <span class="priority"><xsl:value-of select="sitemap:priority"/></span>
                            </xsl:if>
                        </td>
                        <td class="changefreq"><xsl:value-of select="sitemap:changefreq"/></td>
                    </tr>
                </xsl:for-each>
            </table>
        </div>
    </xsl:if>

</div>
</body>
</html>
</xsl:template>

</xsl:stylesheet>
