<?php
/**
 * XML Sitemap generator.
 * Produces sitemap index + individual sitemaps for posts, taxonomies, and (premium) news/video.
 *
 * @package DadsFam_SEO
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class DFSEO_Sitemap {

	/** Posts per sitemap file (to stay under 50k URL limit) */
	const POSTS_PER_SITEMAP = 1000;

	/** Server-side cache: bumping the version option invalidates all cached files at once */
	const CACHE_VERSION_OPT = 'dfseo_sitemap_cache_v';
	const CACHE_TTL         = 12 * HOUR_IN_SECONDS;

	public function __construct() {
		// Disable WordPress core sitemap — ours replaces it completely
		add_filter( 'wp_sitemaps_enabled', '__return_false' );

		add_action( 'init',      [ $this, 'register_rewrite_rules' ] );
		add_action( 'template_redirect', [ $this, 'handle_sitemap_request' ] );
		add_filter( 'robots_txt', [ $this, 'add_sitemap_to_robots' ], 20, 2 );

		// Flush on settings save
		add_action( 'update_option_dfseo_sitemap_post_types',  [ $this, 'flush_rules' ] );
		add_action( 'update_option_dfseo_sitemap_taxonomies',  [ $this, 'flush_rules' ] );

		// Invalidate the cached sitemap whenever content changes
		add_action( 'save_post',              [ __CLASS__, 'bust_cache' ] );
		add_action( 'deleted_post',           [ __CLASS__, 'bust_cache' ] );
		add_action( 'transition_post_status', [ __CLASS__, 'bust_cache' ] );

		// Ping search engines on publish
		add_action( 'publish_post', [ $this, 'ping_search_engines' ], 20 );
	}

	/** Bump the cache version → every cached sitemap file is treated as stale. */
	public static function bust_cache(): void {
		$v = (int) get_option( self::CACHE_VERSION_OPT, 1 );
		update_option( self::CACHE_VERSION_OPT, $v + 1, false );
	}

	private function cache_key( string $type, int $page ): string {
		$v = (int) get_option( self::CACHE_VERSION_OPT, 1 );
		return 'dfseo_sm_' . $v . '_' . preg_replace( '/[^a-z0-9_-]/i', '', $type ) . '_' . $page;
	}

	// ─── Rewrite rules ──────────────────────────────────────────────────────

	public function register_rewrite_rules(): void {
		add_rewrite_rule( '^sitemap\.xml$',                'index.php?dfseo_sitemap=index',       'top' );
		add_rewrite_rule( '^sitemap-index\.xml$',          'index.php?dfseo_sitemap=index',       'top' );
		add_rewrite_rule( '^sitemap-([a-z_-]+)-(\d+)\.xml$', 'index.php?dfseo_sitemap=$matches[1]&dfseo_sitemap_page=$matches[2]', 'top' );
		add_rewrite_rule( '^sitemap-([a-z_-]+)\.xml$',     'index.php?dfseo_sitemap=$matches[1]', 'top' );
		add_rewrite_tag( '%dfseo_sitemap%',      '([^&]+)' );
		add_rewrite_tag( '%dfseo_sitemap_page%', '(\d+)' );
	}

	public static function flush_rewrite_rules_on_activate(): void {
		// Rewrite rules flush happens in DFSEO_Core::activate() after this
	}

	public function flush_rules(): void {
		flush_rewrite_rules();
	}

	// ─── Request handler ────────────────────────────────────────────────────

	public function handle_sitemap_request(): void {
		$type = (string) get_query_var( 'dfseo_sitemap' );
		if ( empty( $type ) ) return;

		header( 'X-Robots-Tag: noindex, follow', true );
		header( 'Content-Type: text/xml; charset=' . get_bloginfo( 'charset' ) );

		$page = max( 1, (int) get_query_var( 'dfseo_sitemap_page' ) ?: 1 );

		// News is time-sensitive (48h window, posts age out) — never cache it.
		$cacheable = ( $type !== 'news' );

		if ( $cacheable ) {
			$cache_key = $this->cache_key( $type, $page );
			$cached    = get_transient( $cache_key );
			if ( is_string( $cached ) && $cached !== '' ) {
				// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped — pre-built, already-escaped XML
				echo $cached;
				exit;
			}
		}

		ob_start();
		switch ( $type ) {
			case 'index':    $this->render_index();             break;
			case 'news':     $this->render_news_sitemap();      break;
			default:
				if ( strpos( $type, 'tax-' ) === 0 ) {
					$this->render_taxonomy_sitemap( substr( $type, 4 ), $page );
				} else {
					$this->render_post_type_sitemap( $type, $page );
				}
		}
		$output = ob_get_clean();

		if ( $cacheable && ! empty( $output ) ) {
			set_transient( $this->cache_key( $type, $page ), $output, self::CACHE_TTL );
		}

		// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped — pre-built, already-escaped XML
		echo $output;
		exit;
	}

	// ─── Index ──────────────────────────────────────────────────────────────

	private function serve_xsl(): void {
		header( 'Content-Type: text/xsl; charset=UTF-8' );
		$file = DFSEO_PATH . 'assets/sitemap.xsl';
		if ( file_exists( $file ) ) {
			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
			echo file_get_contents( $file );
		}
		exit;
	}

	private function render_index(): void {
		$sitemaps = $this->get_sitemap_list();
		echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
		echo '<?xml-stylesheet type="text/xsl" href="' . esc_url( DFSEO_URL . 'assets/sitemap.xsl' ) . '"?>' . "\n";
		echo '<!-- Generated by DadsFam SEO ' . esc_html( DFSEO_VERSION ) . ' -->' . "\n";
		echo '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n";
		foreach ( $sitemaps as $sm ) {
			echo "\t<sitemap>\n";
			echo "\t\t<loc>" . esc_url( $sm['url'] ) . "</loc>\n";
			echo "\t\t<lastmod>" . esc_html( $sm['lastmod'] ) . "</lastmod>\n";
			echo "\t</sitemap>\n";
		}
		echo '</sitemapindex>';
	}

	private function get_sitemap_list(): array {
		$list  = [];
		$types = (array) get_option( 'dfseo_sitemap_post_types', [ 'post', 'page' ] );

		foreach ( $types as $pt ) {
			$obj = get_post_type_object( $pt );
			if ( ! $obj || ! $obj->public ) continue;

			$count = $this->get_post_count( $pt );
			$pages = max( 1, (int) ceil( $count / self::POSTS_PER_SITEMAP ) );

			for ( $p = 1; $p <= $pages; $p++ ) {
				$list[] = [
					'url'     => home_url( "/sitemap-{$pt}-{$p}.xml" ),
					'lastmod' => $this->last_modified_for_type( $pt ),
				];
			}
		}

		// Taxonomies
		$taxs = (array) get_option( 'dfseo_sitemap_taxonomies', [ 'category', 'post_tag' ] );
		foreach ( $taxs as $tax ) {
			if ( ! taxonomy_exists( $tax ) ) continue;
			$list[] = [
				'url'     => home_url( "/sitemap-tax-{$tax}.xml" ),
				'lastmod' => gmdate( 'c' ),
			];
		}

		// News sitemap (premium)
		if ( dfseo_is_premium() ) {
			$list[] = [
				'url'     => home_url( '/sitemap-news.xml' ),
				'lastmod' => gmdate( 'c' ),
			];
		}

		return $list;
	}

	// ─── Post type sitemap ──────────────────────────────────────────────────

	private function render_post_type_sitemap( string $post_type, int $page ): void {
		if ( ! post_type_exists( $post_type ) ) {
			$this->render_404();
			return;
		}

		$exclude = (array) get_option( 'dfseo_sitemap_exclude_ids', [] );

		$posts = get_posts( [
			'post_type'        => $post_type,
			'post_status'      => 'publish',
			'posts_per_page'   => self::POSTS_PER_SITEMAP,
			'offset'           => ( $page - 1 ) * self::POSTS_PER_SITEMAP,
			'post__not_in'     => $exclude,
			'orderby'          => 'modified',
			'order'            => 'DESC',
			'suppress_filters' => true,
			'meta_query'       => [ [ 'key' => '_dfseo_noindex', 'compare' => 'NOT EXISTS' ], [ 'key' => '_dfseo_noindex', 'value' => '1', 'compare' => '!=' ] ],
		] );

		// Also exclude posts manually set to noindex
		$posts = array_filter( $posts, static function( $p ) {
			return get_post_meta( $p->ID, '_dfseo_noindex', true ) !== '1';
		} );

		echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
		echo '<?xml-stylesheet type="text/xsl" href="' . esc_url( DFSEO_URL . 'assets/sitemap.xsl' ) . '"?>' . "\n";
		echo '<!-- DadsFam SEO — ' . esc_html( $post_type ) . ' sitemap page ' . (int) $page . ' -->' . "\n";
		echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">' . "\n";

		foreach ( $posts as $post ) {
			$priority  = $this->get_priority( $post );
			$changefreq = $this->get_changefreq( $post );
			$images    = $this->get_post_images( $post );

			echo "\t<url>\n";
			echo "\t\t<loc>" . esc_url( get_permalink( $post ) ) . "</loc>\n";
			echo "\t\t<lastmod>" . esc_html( mysql2date( 'c', $post->post_modified_gmt, false ) ) . "</lastmod>\n";
			echo "\t\t<changefreq>" . esc_html( $changefreq ) . "</changefreq>\n";
			echo "\t\t<priority>" . esc_html( $priority ) . "</priority>\n";
			foreach ( $images as $img ) {
				echo "\t\t<image:image>\n";
				echo "\t\t\t<image:loc>" . esc_url( $img['src'] ) . "</image:loc>\n";
				if ( $img['title'] ) echo "\t\t\t<image:title>" . esc_html( $img['title'] ) . "</image:title>\n";
				if ( $img['caption'] ) echo "\t\t\t<image:caption>" . esc_html( $img['caption'] ) . "</image:caption>\n";
				echo "\t\t</image:image>\n";
			}
			echo "\t</url>\n";
		}
		echo '</urlset>';
	}

	// ─── Taxonomy sitemap ───────────────────────────────────────────────────

	private function render_taxonomy_sitemap( string $taxonomy, int $page ): void {
		$terms = get_terms( [
			'taxonomy'   => $taxonomy,
			'hide_empty' => true,
			'number'     => self::POSTS_PER_SITEMAP,
			'offset'     => ( $page - 1 ) * self::POSTS_PER_SITEMAP,
		] );

		echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
		echo '<?xml-stylesheet type="text/xsl" href="' . esc_url( DFSEO_URL . 'assets/sitemap.xsl' ) . '"?>' . "\n";
		echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n";

		if ( ! is_wp_error( $terms ) ) {
			foreach ( $terms as $term ) {
				$noindex = (string) get_term_meta( $term->term_id, '_dfseo_noindex', true );
				if ( $noindex === '1' ) continue;
				echo "\t<url>\n";
				echo "\t\t<loc>" . esc_url( get_term_link( $term ) ) . "</loc>\n";
				echo "\t\t<changefreq>weekly</changefreq>\n";
				echo "\t\t<priority>0.6</priority>\n";
				echo "\t</url>\n";
			}
		}
		echo '</urlset>';
	}

	// ─── News sitemap (premium) ──────────────────────────────────────────────

	private function render_news_sitemap(): void {
		if ( ! dfseo_is_premium() ) {
			$this->render_404();
			return;
		}

		$posts = get_posts( [
			'post_type'      => 'post',
			'post_status'    => 'publish',
			'posts_per_page' => 1000,
			'date_query'     => [ [ 'after' => '48 hours ago' ] ],
			'orderby'        => 'date',
			'order'          => 'DESC',
		] );

		$pub_name = get_bloginfo( 'name' );
		$lang     = substr( get_locale(), 0, 2 );

		echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
		echo '<?xml-stylesheet type="text/xsl" href="' . esc_url( DFSEO_URL . 'assets/sitemap.xsl' ) . '"?>' . "\n";
				echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9">' . "\n";

		foreach ( $posts as $post ) {
			echo "\t<url>\n";
			echo "\t\t<loc>" . esc_url( get_permalink( $post ) ) . "</loc>\n";
			echo "\t\t<news:news>\n";
			echo "\t\t\t<news:publication>\n";
			echo "\t\t\t\t<news:name>" . esc_html( $pub_name ) . "</news:name>\n";
			echo "\t\t\t\t<news:language>" . esc_html( $lang ) . "</news:language>\n";
			echo "\t\t\t</news:publication>\n";
			echo "\t\t\t<news:publication_date>" . esc_html( mysql2date( 'c', $post->post_date_gmt, false ) ) . "</news:publication_date>\n";
			echo "\t\t\t<news:title>" . esc_html( $post->post_title ) . "</news:title>\n";
			echo "\t\t</news:news>\n";
			echo "\t</url>\n";
		}
		echo '</urlset>';
	}

	// ─── Helpers ────────────────────────────────────────────────────────────

	private function get_priority( WP_Post $post ): string {
		if ( $post->post_type === 'page' && (int) get_option( 'page_on_front' ) === $post->ID ) return '1.0';
		if ( $post->post_type === 'page' ) return '0.8';
		// More recent = higher priority
		$age_days = ( time() - strtotime( $post->post_date ) ) / DAY_IN_SECONDS;
		if ( $age_days < 7  ) return '0.9';
		if ( $age_days < 30 ) return '0.7';
		return '0.6';
	}

	private function get_changefreq( WP_Post $post ): string {
		$age_days = ( time() - strtotime( $post->post_modified ) ) / DAY_IN_SECONDS;
		if ( $age_days < 1  ) return 'hourly';
		if ( $age_days < 7  ) return 'daily';
		if ( $age_days < 30 ) return 'weekly';
		if ( $age_days < 365 ) return 'monthly';
		return 'yearly';
	}

	private function get_post_images( WP_Post $post ): array {
		$images = [];
		// Featured image
		$thumb_id = (int) get_post_thumbnail_id( $post->ID );
		if ( $thumb_id ) {
			$src     = wp_get_attachment_image_url( $thumb_id, 'full' );
			$caption = get_post( $thumb_id )->post_excerpt ?? '';
			$title   = get_the_title( $thumb_id );
			if ( $src ) $images[] = [ 'src' => $src, 'title' => $title, 'caption' => $caption ];
		}
		// In-content images (limit to 5)
		preg_match_all( '/<img[^>]+src=["\']([^"\']+)["\'][^>]*>/i', $post->post_content, $m );
		$count = 0;
		foreach ( $m[1] ?? [] as $src ) {
			if ( $count >= 5 ) break;
			$images[] = [ 'src' => $src, 'title' => '', 'caption' => '' ];
			$count++;
		}
		return $images;
	}

	private function get_post_count( string $post_type ): int {
		$counts = wp_count_posts( $post_type );
		return $counts ? (int) $counts->publish : 0;
	}

	private function last_modified_for_type( string $post_type ): string {
		global $wpdb;
		// phpcs:ignore WordPress.DB.DirectDatabaseQuery
		$date = $wpdb->get_var( $wpdb->prepare(
			"SELECT post_modified_gmt FROM {$wpdb->posts} WHERE post_type = %s AND post_status = 'publish' ORDER BY post_modified_gmt DESC LIMIT 1",
			$post_type
		) );
		return $date ? mysql2date( 'c', $date, false ) : gmdate( 'c' );
	}

	private function render_404(): void {
		status_header( 404 );
		echo '<?xml version="1.0"?><error>Not found</error>';
		exit;
	}

	// ─── Robots.txt ─────────────────────────────────────────────────────────

	public function add_sitemap_to_robots( string $output, bool $public ): string {
		if ( $public ) {
			$output .= "\nSitemap: " . home_url( '/sitemap.xml' ) . "\n";
		}
		return $output;
	}

	// ─── Ping ───────────────────────────────────────────────────────────────

	/**
	 * Notify search engines that content changed.
	 *
	 * Google permanently shut down its sitemap ping endpoint
	 * (https://www.google.com/ping?sitemap=) in 2023, and Bing deprecated
	 * its equivalent in favour of IndexNow. So instead of pinging dead URLs,
	 * we submit the freshly published post through IndexNow — which instantly
	 * notifies Bing, Yandex, DuckDuckGo, Seznam and every other IndexNow
	 * participant. Google continues to discover the sitemap automatically via
	 * Search Console (and the IndexNow auto-submit in the Indexing module).
	 */
	public function ping_search_engines( $post_id = 0 ): void {
		if ( get_option( 'dfseo_ping_engines', '1' ) !== '1' ) return;
		if ( ! class_exists( 'DFSEO_Indexing' ) ) return;

		$url = $post_id ? get_permalink( (int) $post_id ) : home_url( '/' );
		if ( ! $url ) return;

		$indexing = new DFSEO_Indexing();
		// IndexNow covers Bing + Yandex + DuckDuckGo + Seznam + Naver in one call.
		$indexing->submit_to_indexnow( $url );
	}
}
